version: '3.8'

services:
  opal-vanguard:
    build: .
    container_name: opal-vanguard-receiver
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true
    tty: true
    environment:
      - TF_XLA_FLAGS=--tf_xla_enable_xla_devices=false
    command: python3 train_resnet.py
